let
    // ══════════════════════════════════════════════════════════════
    // NFS-e × SISAP — slim para reconciliação
    // Apenas notas onde Elecnor é Tomadora ou Intermediária
    // Locale en-US nas colunas numéricas (CSV usa ponto como decimal)
    // ══════════════════════════════════════════════════════════════

    CaminhoNFSe = "C:\Users\caio.nascimento\Desktop\nfse_edb\dados\nfse_consolidado.csv",

    // ── 1. Leitura ────────────────────────────────────────────────
    Fonte      = Csv.Document(File.Contents(CaminhoNFSe),
                     [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Cabecalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars = true]),

    // ── 2. Seleciona colunas necessárias ─────────────────────────
    ColunasNecessarias = Table.SelectColumns(Cabecalhos, {
        "Chave NFS-e",
        "Número NFS-e",
        "Data Emissão",
        "Competência",
        "Situação",
        "Unidade Elecnor",
        "Papel Elecnor",
        "CNPJ Prestador",
        "Nome Prestador",
        "Valor Serviço",
        "Valor Líquido",
        "Tem Evento",
        "Tipo Evento",
        "Data Evento"
    }),

    // ── 3. Tipagem — texto e datas ────────────────────────────────
    TipadoTexto = Table.TransformColumnTypes(ColunasNecessarias, {
        {"Chave NFS-e",     type text},
        {"Número NFS-e",    type text},
        {"Data Emissão",    type date},
        {"Competência",     type date},
        {"Situação",        type text},
        {"Unidade Elecnor", type text},
        {"Papel Elecnor",   type text},
        {"CNPJ Prestador",  type text},
        {"Nome Prestador",  type text},
        {"Tem Evento",      type text},
        {"Tipo Evento",     type text},
        {"Data Evento",     type text}
    }),

    // ── 4. Tipagem — numérico com locale en-US ────────────────────
    // CSV usa ponto como decimal (614.49). Em pt-BR o PBI leria como 61449.
    // Forçar en-US garante leitura correta independente da configuração regional.
    Tipado = Table.TransformColumnTypes(TipadoTexto, {
        {"Valor Serviço",  Currency.Type},
        {"Valor Líquido",  Currency.Type}
    }, "en-US"),

    // ── 5. Filtro de papel ────────────────────────────────────────
    // Mantém apenas notas onde a Elecnor é contratante (tomadora ou intermediária)
    // Notas onde a Elecnor é prestadora não entram no cruzamento com SISAP
    FiltradoPapel = Table.SelectRows(
        Tipado,
        each [Papel Elecnor] = "Tomadora" or [Papel Elecnor] = "Intermediária"
    ),

    // ── 6. Colunas calculadas — período ──────────────────────────
    ComAno    = Table.AddColumn(FiltradoPapel, "Ano",
                    each if [Competência] = null then null
                         else Date.Year([Competência]), Int64.Type),
    ComMesNum = Table.AddColumn(ComAno, "Mês Número",
                    each if [Competência] = null then null
                         else Date.Month([Competência]), Int64.Type),
    ComAnoMes = Table.AddColumn(ComMesNum, "Ano-Mês",
                    each if [Ano] = null then null
                         else Text.From([Ano]) & "-" &
                              Text.PadStart(Text.From([#"Mês Número"]), 2, "0"),
                    type text),

    // ── 7. Cancelada ──────────────────────────────────────────────
    ComCancelada = Table.AddColumn(ComAnoMes, "Cancelada",
                       each if [Situação] = "Cancelada" then "Sim" else "Não",
                       type text),

    // ── 8. Substituta ─────────────────────────────────────────────
    ComSubstituta = Table.AddColumn(ComCancelada, "Substituta",
                        each if [Situação] = "Gerada em Substituição" then "Sim" else "Não",
                        type text),

    // ── 9. Chave composta para cruzamento com SISAP ───────────────
    // Chave = CNPJ (14) + Número NFS-e + Data Emissão (YYYY-MM-DD)
    // Mais robusta que só CNPJ+Número — evita colisão com NF modelo 55
    ComChave = Table.AddColumn(
        ComSubstituta, "Chave_SISAP",
        each
            let
                cnpj = Text.PadStart(
                           Text.Select(Text.From([CNPJ Prestador] ?? ""), {"0".."9"}),
                           14, "0"),
                num  = Text.Trim(Text.From([#"Número NFS-e"] ?? "")),
                dt   = if [Data Emissão] = null then ""
                       else Date.ToText([Data Emissão], "yyyy-MM-dd")
            in cnpj & "|" & num & "|" & dt,
        type text
    ),

    // ── 10. Merge com SISAP ───────────────────────────────────────
    SisapBuffer = Table.Buffer(Historico_Sisap),
    Merged      = Table.NestedJoin(
                      ComChave, {"Chave_SISAP"},
                      SisapBuffer, {"Chave_SISAP"},
                      "Info_Sisap", JoinKind.LeftOuter),
    Expandido   = Table.ExpandTableColumn(
                      Merged, "Info_Sisap",
                      {
                          "Fornecedor", "Nome do provedor",
                          "Destino", "Nome do destino",
                          "Num. transação", "Prova Total ML", "Saldo ML",
                          "Contabilizado", "Pago"
                      },
                      {
                          "Cód. Fornecedor SISAP", "Nome Fornecedor SISAP",
                          "Destino SISAP", "Nome Destino SISAP",
                          "Num. Transação SISAP", "Valor SISAP", "Saldo SISAP",
                          "Contabilizado", "Pago"
                      }),

    // ── 11. Existe no SISAP ───────────────────────────────────────
    ComSisap = Table.AddColumn(Expandido, "Existe no SISAP",
                   each if [Cód. Fornecedor SISAP] = null then "Não" else "Sim",
                   type text),

    // ── 12. Alerta ────────────────────────────────────────────────
    ComAlerta = Table.AddColumn(
        ComSisap, "Alerta",
        each
            if [Cancelada] = "Sim" and [Existe no SISAP] = "Não"
            then "OK"
            else if [Cancelada] = "Sim" and [Pago] = "Sim"
            then "Cancelada e paga — verificar"
            else if [Cancelada] = "Sim" and [Contabilizado] = "Sim" and [Pago] = "Não"
            then "Cancelada e contabilizada — estornar"
            else if [Cancelada] = "Sim" and [Contabilizado] = "Não" and [Existe no SISAP] = "Sim"
            then "Cancelada no SISAP — baixar"
            else if [Cancelada] = "Não" and [Existe no SISAP] = "Não"
            then "Gerada — lançar no SISAP"
            else "OK",
        type text
    ),

    // ── 13. Limpeza final ─────────────────────────────────────────
    SemChave = Table.RemoveColumns(ComAlerta, {"Chave_SISAP"}),
    Limpo    = Table.SelectRows(SemChave,
                   each [#"Chave NFS-e"] <> null and [#"Chave NFS-e"] <> ""),
    Ordenado = Table.Sort(Limpo,
                   {{"Competência", Order.Descending}, {"Unidade Elecnor", Order.Ascending}})

in
    Ordenado
